apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-app
  template:
    metadata:
      labels:
        app: book-app
    spec:
      containers: 
      - name: book-app
        image: book-app:1
        imagePullPolicy: Never
        env:
        - name: PORT
          value: "4000"
        - name: DATABASE_URL
          value: postgresql://sit722_postgresql_pxw9_user:IN6PnafKp4so64uM8YTeXoHyponKUGAb@dpg-cs55bc08fa8c73ag42m0-a.oregon-postgres.render.com/sit722_postgresql_pxw9
---
apiVersion: v1
kind: Service
metadata:
  name: book-app
spec:
  selector:
    app: book-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30000